### ISSUE TITLE
请问您是使用skpm生成的项目结构嘛

### ISSUE THREAD

**Issue by Nealyang** [1217950746/Smile-Sketch#1]
我看官网文档是通过skpm生成的项目结构，然后源码文件在src中，
![image](https://user-images.githubusercontent.com/9313216/33596928-a2035f14-d9d8-11e7-9101-039f81bb14f9.png)
请问您是使用skpm生成的项目架构嘛？想学习下您的源码

**Comment by oneo-me** [comment]
我都用过，不过最后直接手写了，搞那么多花样，很麻烦的
